# Generated by Django 2.0.4 on 2018-04-13 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('high', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('low', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('close', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('volume', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(choices=[(0, 'Officer'), (1, 'Director')], default=0)),
                ('insider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='stocks.Insider')),
            ],
            options={
                'default_related_name': 'relations',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date', models.DateField()),
                ('transaction_type', models.CharField(max_length=255)),
                ('owner_type', models.PositiveSmallIntegerField(choices=[(0, 'direct'), (1, 'indirect')], default=0)),
                ('shares_traded', models.IntegerField(default=0)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('shares_held', models.IntegerField(default=0)),
                ('insider_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='stocks.Relation')),
            ],
        ),
        migrations.AddField(
            model_name='relation',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='stocks.Stock'),
        ),
        migrations.AddField(
            model_name='price',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.Stock'),
        ),
    ]
