# Generated by Django 2.0.4 on 2018-04-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ('last_date', 'insider_relation__insider__full_name')},
        ),
        migrations.AlterField(
            model_name='relation',
            name='position',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Officer'), (1, 'Director'), (2, 'Other')], default=0),
        ),
    ]
